export type ErrorType = 'CORRECT' | 'CONCEPT_CONFUSION' | 'CALCULATION_ERROR' | 'PROCEDURE_ERROR' | 'CARELESS_ERROR' | 'TIME_PRESSURE' | 'DIFFICULTY_FAILURE' | 'REPEATED_MISTAKE'
export interface Student { id: number; name: string; created_at: string }
export type OptionKey = 'A' | 'B' | 'C' | 'D'
export interface Question { question_id: number; topic: string; subtopic: string | null; difficulty: 1 | 2 | 3 | 4 | 5; question_text: string; option_a: string; option_b: string; option_c: string; option_d: string; estimated_time: number }
export interface Attempt { attempt_id: number; student_id: number; question_id: number; selected_option: 'A' | 'B' | 'C' | 'D'; correct: boolean; response_time: number; timestamp: string; attempt_number: number }
export interface MistakeEvent { mistake_event_id: number; student_id: number; attempt_id: number; error_type: ErrorType; topic: string; subtopic: string | null; timestamp: string }
export interface AttemptSubmission { attempt: Attempt; mistake_event: MistakeEvent | null; prediction: Prediction | null; prediction_status: string; correct_option: OptionKey; correct_answer: string }
export interface LearnerState { id: number; student_id: number; updated_at: string; mistake_frequency: number; mistake_recency: number; repetition_score: number; difficulty_sensitivity: number; behavior_pressure: number; concept_confusion: number; knowledge_stability: number; mistake_momentum: number; attempt_count: number; relevant_mistake_count: number }
export type AnalyticsTrend = 'IMPROVING' | 'STABLE' | 'DECLINING' | 'INSUFFICIENT_DATA'
export type MistakeTrend = 'INCREASING' | 'STABLE' | 'DECREASING' | 'INSUFFICIENT_DATA'
export interface PerformanceRow { attempts: number; correct: number; incorrect: number; accuracy: number | null; recent_accuracy: number | null; recent_attempts: number; mistake_count: number; difficulty_average: number | null; trend: AnalyticsTrend; trend_value: number | null; trend_sample_sizes: { recent: number; previous: number } }
export interface DifficultyPerformance { difficulty: 1 | 2 | 3 | 4 | 5; attempts: number; correct: number; incorrect: number; accuracy: number | null; mistake_rate: number | null; average_response_time: number | null }
export interface TrajectoryPoint { attempt_number: number; timestamp: string | null; accuracy: number; difficulty: number; mistake_rate: number; rolling_accuracy: number | null; rolling_mistake_rate: number | null; learning_stability: number }
export interface ProgressSummary { total_attempts: number; total_correct: number; total_incorrect: number; overall_accuracy: number; recent_accuracy: number | null; recent_window_size: number; recent_sample_size: number; improvement_value: number | null; improvement_direction: AnalyticsTrend; sample_sizes: { recent: number; previous: number }; window_size: number; configured_window_size?: number; topics_practiced: number; mistake_count: number; repeated_mistake_count: number; successful_high_difficulty_attempts: number; high_difficulty_attempts: number; current_streak: number; best_streak: number }
export interface Progress { student_id: number; attempt_count: number; correct_count: number; accuracy: number; mistake_count: number; summary?: ProgressSummary; topic_performance?: Array<PerformanceRow & { topic: string }>; subtopic_performance?: Array<PerformanceRow & { topic: string; subtopic: string }>; difficulty_performance?: DifficultyPerformance[]; trajectory?: TrajectoryPoint[]; difficulty_trajectory?: Array<{ attempt_number: number; timestamp: string | null; difficulty: number; correct: boolean }>; recovery?: { window_attempts: number; recovery_count: number; eligible_mistakes: number; recovery_rate: number | null; average_recovery_attempts: number | null; sample_sufficient: boolean }; stability?: { value: number | null; status: 'STABLE' | 'IMPROVING' | 'VARIABLE' | 'NEEDS_MORE_DATA'; sample_size: number; source: string | null }; mistake_momentum?: { value: number | null; direction: MistakeTrend; trend?: MistakeTrend; sample_size: number; source: string | null } }
export interface MistakeSummary { student_id: number; mistake_count: number; attempt_count: number; distribution: Array<{ error_type: ErrorType; occurrences: number; percentage_of_mistakes: number; recent_frequency: number | null; recent_occurrences: number; trend: MistakeTrend; trend_value: number | null }>; recent_frequency: number | null; trend: MistakeTrend; timeline_bucket: 'daily' | 'weekly'; timeline: Array<{ period: string; occurrences: number }>; timeline_sufficient: boolean; timeline_message: string | null; repeated: Array<{ error_type: string; topic: string; subtopic: string | null; occurrences: number; last_occurrence: string | null; recent_occurrences: number; trend: MistakeTrend }>; confusions: { nodes: string[]; edges: Array<{ concept_a: string; concept_b: string; occurrences: number; recent_occurrences: number; last_occurrence: string | null; strength: number | null; trend: MistakeTrend }> }; recent_mistakes: MistakeEvent[] }
export interface Prediction { id: number; student_id: number; prediction: ErrorType; probability: number; confidence: number; reliability: number; status: string; model: string; model_version: string; context_question_id: number | null; timestamp: string; top_predictions?: Array<{ error_type: ErrorType; probability: number }> }
export interface PredictionExplanation { prediction: ErrorType; probability: number; risk_score: number; reasons: Array<{ feature: string; value: number; weight: number; contribution: number }>; top_predictions: Array<{ error_type: ErrorType; probability: number }>; summary?: string; evidence: string[]; learning_need: string[] }
export interface Recommendation { id: number; student_id: number; type: string; reason: string; created_at: string; question_id: number | null; score: number | null; score_components: Record<string, number> | null; completed_at: string | null }
export interface RecommendedPractice { recommendation: Recommendation; question: Question; cold_start: boolean }
