from enum import Enum


class ErrorType(str, Enum):
    CORRECT = "CORRECT"
    CONCEPT_CONFUSION = "CONCEPT_CONFUSION"
    CALCULATION_ERROR = "CALCULATION_ERROR"
    PROCEDURE_ERROR = "PROCEDURE_ERROR"
    CARELESS_ERROR = "CARELESS_ERROR"
    TIME_PRESSURE = "TIME_PRESSURE"
    DIFFICULTY_FAILURE = "DIFFICULTY_FAILURE"
    REPEATED_MISTAKE = "REPEATED_MISTAKE"
